WebTest2/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using WebTest2.Models;

namespace WebTest2.Controllers
{
    public class LandingController : Controller
    {
        // GET: Landing
        public ActionResult Index()
        {
            using (var context = new DBModels())
            {
                var listMN = new listModuleName();
                listMN.list_Module_Name_ = new list_module_name_table();
                listMN.list_Module_Name_Tables = context.list_module_name_table.ToList();
                return View(listMN);
            }
        }
        /*public Boolean Check_Specialchar(string module_name)
        {
            string pattern = @"(\s+|@|&|!|\$|%|\^|#)";
            var regexItem = new Regex(pattern);
            if (regexItem.IsMatch(module_name)) {return true;}return false;
        }*/
        public Boolean Check_Specialchar(string module_name)
        {
            var withoutSpecial = new string(module_name.Where(c => Char.IsLetterOrDigit(c)
                                            || Char.IsWhiteSpace(c)).ToArray());

            if (module_name != withoutSpecial)
            {
                return true;
            }
            return false;
        }

        //check_duplicate_test_case_name()
        public Boolean Check_Duplicate_Module_Name(string case_name)
        {
            using (var context = new DBModels())
            {
                bool result = context.list_module_name_table.Any(u => u.name_of_module == case_name);
                return result;
            }

        }
        
        [HttpPost]
        public ActionResult Add_Module_name(listModuleName model)
        {
            String status = "false";
            String message = "";
            if (ModelState.IsValid)
            {
                using (var context = new DBModels())
                {
                    try
                    {

                        //string module_name = Regex.Replace(model.list_Module_Name_.name_of_module, @"(\s+|@|&|!|\$|%|\^|#)", "");
                        if (Check_Specialchar(model.list_Module_Name_.name_of_module) == true)
                        {
                            return Json(new { status = "false", message = "Special Char is invalid" });
                        }
                        //model.list_Module_Name_.name_of_module = module_name;
                        bool res = Check_Duplicate_Module_Name(model.list_Module_Name_.name_of_module);
                        if (res)
                        {
                            return Json(new { status = "false", message = "Already have modules" });
                        }
                        else
                        {
                            //add module to list_module
                            context.list_module_name_table.Add(model.list_Module_Name_);
                            var response = context.SaveChanges();

                            status = "true";
                            message = "Successfully";
                        }

                    }
                    catch (Exception ex)
                    {
                        status = "false";
                        message = ex.Message;
                    }
                }
            }
            else
            {
                return Json(new
                {
                    status = status,
                    message = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage))
                });
            }
            if (status == "true")
            {
                //TempData["Message"] = message;
                //TempData["Status"] = status;
                return Json(new { status = status, message = message });
            }
            else
            {
                //ViewBag.Message = message;
                //ViewBag.Status = status;
                return Json(new { status = status, message = message });
            }
        }
        
        [HttpPost]
        public ActionResult Edit_Module_name(listModuleName model)
        {
            String status = "false";
            String message = "";
            if (ModelState.IsValid)
            {
                using (var context = new DBModels())
                {
                    try
                    {
                        //string module_name = Regex.Replace(model.list_Module_Name_.name_of_module, @"(\s+|@|&|!|\$|%|\^|#)", "");
                        if (Check_Specialchar(model.list_Module_Name_.name_of_module) == true) { 
                            return Json(new { status = "false", message = "Special Char is invalid" });
                        }
                        //model.list_Module_Name_.name_of_module = module_name;
                        bool res = Check_Duplicate_Module_Name(model.list_Module_Name_.name_of_module);
                        if (res)
                        {
                            //ViewBag.status = "false";
                            //ViewBag.Message = "Already have modules";
                            return Json(new { status = "false", message = "Already have modules" });
                        }
                        else
                        {
                            string module_id = Request["module_id"];
                            int module_id_int = Int32.Parse(module_id);
                            var result = context.list_module_name_table.First(a => a.module_id == module_id_int);
                            if (result != null)
                            {
                                result.name_of_module = model.list_Module_Name_.name_of_module;
                                var response = context.SaveChanges();
                                status = "true";
                                message = "Successfully";
                            }
                        }

                    }
                    catch (Exception ex)
                    {
                        status = "false";
                        message = ex.Message;
                    }
                }
            }
            else
            {
                return Json(new
                {
                    status = status,
                    message = string.Join("; ", ModelState.Values
                                                        .SelectMany(x => x.Errors)
                                                        .Select(x => x.ErrorMessage))
                });
            }
            if (status == "true")
            {
                //TempData["Message"] = message;
                //TempData["Status"] = status;
                return Json(new { status = status, message = message });
            }
            else
            {
                //ViewBag.Message = message;
                //ViewBag.Status = status;
                return Json(new { status = status, message = message });
            }
        }

        [HttpPost]
        public ActionResult Delete_Module_name(string id, string module_name)
        {
            String status = "false";
            String message = "";
            var id2 = Int32.Parse(id);
            using (var context = new DBModels())
            {
                try
                {
                    var itemToRemove = context.list_module_name_table.SingleOrDefault(x => x.module_id == id2 && x.name_of_module == module_name);

                    if (itemToRemove != null)
                    {
                        context.list_module_name_table.Remove(itemToRemove);
                        var res = context.SaveChanges();
                        status = "true";
                        message = "Successfully";
                    }
                    else
                    {
                        //TempData["Message"] = "module_id && module_name not found";
                        //TempData["Status"] = status;
                        //ยังไม่ส่งอะไรไปแสดง
                        return Json(new { status = status, message = "module_id && module_name not found" });
                    }


                }
                catch (Exception ex)
                {
                    status = "false";
                    message = ex.Message;
                }
            }
            //TempData["Message"] = message;
            //TempData["Status"] = status;
            return Json(new { status = status, message = message });          
        }


    }

    
}

WebTest2/Controllers/RTMController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTest2.Models;

namespace WebTest2.Controllers
{
    public class RTMController : Controller
    {
        public ActionResult RTM(int id, string module_name)
        {

            using (var context = new DBModels())
            {
                //var rtm_data = context.rtm_table.Where(s => s.module_id == id).ToList();
                var listRTM = new listRTM();
                listRTM.rtm_Table = new rtm_table();
                listRTM.rtm_Tables = context.rtm_table.Where(s => s.module_id == id).ToList();
                ViewBag.Module_id = id;
                ViewBag.MName = module_name;
                return View(listRTM);
            }

        }
        [HttpPost]
        public ActionResult Add_New_RTM(listRTM model)
        {
            String status = "false";
            String message = "";
            using (var context = new DBModels())
            {
                if (ModelState.IsValid)
                {                   
                    try
                    {
                        
                        string module_id = Request["module_id"];
                        int module_id_2 = Int32.Parse(module_id);
                        string module_name1 = "";
                        var module_name = context.list_module_name_table.Where(s => s.module_id == module_id_2).ToList();
                        module_name1 = module_name[0].name_of_module;
                        if (model.rtm_Table.comments == "" || model.rtm_Table.comments == null)
                        {
                            model.rtm_Table.comments = "Null";
                        }
                        model.rtm_Table.module_id = module_id_2;
                        context.rtm_table.Add(model.rtm_Table);
                        var response = context.SaveChanges();

                        status = "true";
                        message = "Successfully";
                    }
                    catch (Exception ex)
                    {
                        /*DbEntityValidationException e
                        foreach (var eve in e.EntityValidationErrors)
                        {
                            Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                eve.Entry.Entity.GetType().Name, eve.Entry.State);
                            foreach (var ve in eve.ValidationErrors)
                            {
                                Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                    ve.PropertyName, ve.ErrorMessage);
                            }
                        }
                        throw;
                        */
                        return Json(new { status = status, message = ex.Message });
                    }                    
                    return Json(new { status = status, message = message });
                }
                else
                {
                    return Json(new {
                        status = status,
                        message = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage))
                    });
                }
            }            
        }

        public ActionResult Edit_RTM()
        {
            String status = "false";
            String message = "";                               
                using (var context = new DBModels())
                {
                    try
                    {
                        int module_id = Int32.Parse(Request["module_id"]);                       
                        int req_id = Int32.Parse(Request["req_id"]);
                        string des = Request["item.value.req_description"];
                        int desing_spec = Int32.Parse(Request["item.value.design_specification_reference_number"]);
                        string pro_module = Request["item.value.program_module"];
                        int test_refer = Int32.Parse(Request["item.value.test_reference_number"]);
                        string statusr = Request["item.value.status"];
                        DateTime status_date = DateTime.Parse(Request["item.value.status_date"]);
                        string comment = Request["item.value.comments"];
                        if (comment == "" || comment == null)
                        {
                            comment = "Null";
                        }
                    var result = context.rtm_table.First(a => a.module_id == module_id && a.req_id == req_id);
                        if (result != null)
                        {
                            result.req_description = des;
                            result.program_module = pro_module;
                            result.status = statusr;
                            result.status_date = status_date;
                            result.test_reference_number = test_refer;
                            result.design_specification_reference_number = desing_spec;
                            result.comments = comment;
                            var response = context.SaveChanges();
                            status = "true";
                            message = "Successfully";
                        }                 
                    }
                    catch (Exception ex)
                    {
                        status = "false";
                        message = ex.Message;
                    }
                }         
            if (status == "true")
            {
                return Json(new { status = status, message = message });
            }
            else
            {
                return Json(new { status = status, message = message });
            }
        }
        public ActionResult Delete_RTM(string id ,string rtm_data, string mid)
        {
            String status = "false";
            String message = "";
            using (var context = new DBModels())
            {
                try
                {
                    int id2 = Int32.Parse(id);
                    int module_id = Int32.Parse(mid);
                    var itemToRemove = context.rtm_table.SingleOrDefault(x => x.req_id == id2 && x.module_id == module_id);

                    if (itemToRemove != null)
                    {
                        context.rtm_table.Remove(itemToRemove);
                        var response = context.SaveChanges();
                        status = "true";
                        message = "Successfully";
                    }
                    else
                    {
                        return Json(new { status = status, message = "req_id && module_id not found" });
                        //TempData["Message"] = "req_id && module_id not found";
                        //TempData["Status"] = status;
                    }


                }
                catch (Exception ex)
                {
                    status = "false";
                    message = ex.Message;
                }
            }
            //TempData["MessageRTM"] = message;
            //TempData["StatusRTM"] = status;
            return Json(new { status = status, message = message });
        }
    }
}

WebTest2/Views/Landing/Index.cshtml
@*@model IEnumerable<WebTest2.Models.list_module_name_table>*@
@model WebTest2.Models.listModuleName
@{
    ViewBag.Title = "Index";
}
@Html.Raw(TempData["msg"])
<h2>Module List</h2>

@*<button type="button" class="btn btn-light">@Html.ActionLink("Add New Module", "add_new_module")</button>*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModule">Add New Module</button>
<br>
<br>

@if (TempData["Message"] != null && TempData["Status"].ToString() == "true")
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"].ToString()
    </div>
}

<div class="container-fluid" id="module_box">
    <div class="row">
        @try
        {
            foreach (var item in Model.list_Module_Name_Tables)
            {


                <div class="col-md-4 col-xl-3">
                    <div class="card bg-c-blue order-card">
                        <div class="card-block">
                            <h4 class="m-b-20" id="module_name">@Html.DisplayFor(modelItem => item.name_of_module)</h4>
                            <p class="m-b-0">
                                <span class="f-right">
                                    @Html.ActionLink("Go", "RTM", "RTM", new { id = item.module_id, module_name = item.name_of_module }, new { @class = "text-dark" })
                                    <a href="#editModule" id="edit_mname" data-module-id="@Html.DisplayFor(modelItem => item.module_id)" data-modulename-id="@Html.DisplayFor(modelItem => item.name_of_module)" class="text-dark" data-toggle="modal">Edit</a>
                                    <a href="#" name="del_mn" id="del_mn" class="text-dark" onclick='delmn("@item.name_of_module","@item.module_id");'>Del</a>
                                </span>
                            </p>
                        </div>
                    </div>
                </div>



            }
        }
        catch (Exception ex)
        {
            <label>@ex.Message</label>
        }
    </div>
</div>

@*add module
*@
@using (Ajax.BeginForm("Add_Module_name", "Landing", new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxAddSuccess(data);", OnFailure = "ajaxAddUnSuccess(data);" }))
{
    @Html.AntiForgeryToken()

    <div class="modal fade" id="addModule" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <form id="addNewModule">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add New Module</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="modal-body">
                        <div class="form-group">
                            @Html.EditorFor(x => x.list_Module_Name_.name_of_module, new { htmlAttributes = new { @class = "form-control", @id = "name_of_module", @name = "name_of_module", @maxlength = 50, @placeholder = "Add Module Name" } })
                            @Html.ValidationMessageFor(x => x.list_Module_Name_.name_of_module, "", new { @class = "text-danger", @id = "validateAdd" })
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Submit" id="btnSave" class="btn btn-primary" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
}
@*edit module
*@
@using (Ajax.BeginForm("Edit_Module_name", "Landing", new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxEditSuccess(data);", OnFailure = "ajaxEditUnSuccess(data);" }))
{
    @Html.AntiForgeryToken()

    <div class="modal fade" id="editModule" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <form id="editNewModule">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Module <label name="module_name_rt" id="module_name_rt" class="control-label" /></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="modal-body">
                        <div class="form-group">
                            @Html.EditorFor(x => x.list_Module_Name_.name_of_module, new { htmlAttributes = new { @class = "form-control", @id = "edit_name_of_module", @name = "edit_name_of_module", @maxlength = 50, @placeholder = "Edit Module Name" } })
                            @Html.ValidationMessageFor(x => x.list_Module_Name_.name_of_module, "", new { @class = "text-danger", @id = "validateEdit" })
                        </div>
                    </div>
                    <input type="hidden" name="module_id" id="module_id" value="" />
                    <div class="modal-footer">
                        <input type="submit" value="Submit" id="btnSave" class="btn btn-primary" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
}
@*render javascript*@
@section Scripts
{
    <script>
        var ajaxAddSuccess = function (data) {
            if (data.status == "true") {
                //debugger;
                alert(data.message);
                $("#module_box").load(" #module_box > *");
                $('#addModule').modal('hide');
            } else {
                //debugger;
                alert(data.message);
            }
        }

        var ajaxAddUnSuccess = function (data) {
            if (data.status == "true") {
                alert(data.message);
            } else {
                alert(data.message);
            }
            //$("#module_box").load(" #module_box > *");
            //$('#editModule').modal('hide');
        }

        var ajaxEditSuccess = function (data) {
            if (data.status == "true") {
                //debugger;
                alert(data.message);
                $("#module_box").load(" #module_box > *");
                $('#editModule').modal('hide');
            } else {
                //debugger;
                alert(data.message);
            }

        }

        var ajaxEditUnSuccess = function (data) {
            if (data.status == "true") {
                alert(data.message);
            } else {
                alert(data.message);
            }
            //$("#module_box").load(" #module_box > *");
            //$('#editModule').modal('hide');
        }

        $('#addModule').on('shown.bs.modal', function () {
            $('#name_of_module').trigger('focus');
            //$.validator.unobtrusive.parse("#addNewModule");
        });
        $("#addModule").on("hidden.bs.modal", function () {
            $("#validateAdd").html("");
            $("#name_of_module").val("");
        });

        //$.validator.unobtrusive.parse("#editNewModule");
        $('#editModule').on('show.bs.modal', function (e) {

            //get data-id attribute of the clicked element

            var Id = $(e.relatedTarget).data('module-id');
            var module_name = $(e.relatedTarget).data('modulename-id');
            //debugger;
            $(e.currentTarget).find('label[name="module_name_rt"]').text(module_name);
            //$(e.currentTarget).find('input[name="module_name_rt"]').val(module_name);
            $(e.currentTarget).find('input[name="module_id"]').val(Id);
            //var data_a = $(e.currentTarget).find('input[name="module_id"]');
            //document.getElementById('module_id').innerHTML += Id;
        });
        $("#editModule").on("hidden.bs.modal", function () {
            $("#validateEdit").html("");
            $("#edit_name_of_module").val("");
        });

        function delmn(Name, ID) {
            //debugger;
            var ans = confirm("Are you sure you want to delete " + Name + " ? ");
            if (ans) {
                $.ajax({
                    url: "/Landing/Delete_Module_name",
                    type: "POST",
                    dataType: "json",
                    data: { 'id': ID, 'module_name': Name },
                    success: function (result) {
                        if (result.status == "true") {
                            alert(result.message);
                        } else {
                            alert(result.message);
                        }
                        $("#module_box").load(" #module_box > *");
                    },
                    error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }

                        alert(msg);
                    }
                });
            }
        }







    </script>

}