WebTest2/Controllers/AddFactorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTest2.Models;

namespace WebTest2.Controllers
{
    public class AddFactorsController : Controller
    {
        // GET: AddFactors
        public ActionResult Display_Factors(int id, string module_name)
        {
            using (var context = new DBModels())
            {
                /*Get data from another controller.
                 * var controller = DependencyResolver.Current.GetService<FactorsController>();
                 * controller.ControllerContext = new ControllerContext(this.Request.RequestContext, controller);
                 * int cal = controller.Calculate_Items(id);
                 * ViewBag.TotalFactor = cal;
                 */
                listFactors listF = new listFactors();
                listF.factors_Name_Table = new factors_name_table();
                listF.factors_Name_Tables = context.factors_name_table.Where(s => s.module_id == id).ToList();
                ViewBag.Module_id = id;
                ViewBag.MName = module_name;                                             
                return View(listF);
            }
        }
        //ยังไม่เพิ่มในเอกสาร
        public Boolean check_duplicate_factors_name(string factor_name, int module_id)
        {
            using (var context = new DBModels())
            {
                bool result = context.factors_name_table.Any(u => u.fn_name == factor_name && u.module_id == module_id);
                return result;
            }

        }
        public ActionResult Add_new_Factors(listFactors model)
        {
            String status = "false";
            String message = "form is not valid";       
            string module_name1 = "";
            if (ModelState.IsValid)
            {
                using (var context = new DBModels())
                {                       
                    try
                    {
                        if(model.factors_Name_Table.fn_name == "")
                        {
                            return Json(new { status = "false", message = "Factors name is Empty" });
                        }
                        int module_id = Int32.Parse(Request["module_id"]);
                        var module_name = context.list_module_name_table.Where(s => s.module_id == module_id).ToList();
                        module_name1 = module_name[0].name_of_module;
                        //case sensitive ยังไม่เขียนในเอกสาร
                        bool res = check_duplicate_factors_name(model.factors_Name_Table.fn_name, module_id);
                        if (res)
                        {
                            return Json(new { status = "false", message = "Already have Factor" });
                        }
                        else
                        {
                            model.factors_Name_Table.module_id = module_id;
                            context.factors_name_table.Add(model.factors_Name_Table);
                            var response = context.SaveChanges();

                            status = "true";
                            message = "Successfully";
                        }

                    }
                    catch (Exception ex)
                    {
                        status = "false";
                        message = ex.Message;
                    }
                }
            }
            else
            {
                return Json(new
                {
                    status = "false",
                    message = string.Join("; ", ModelState.Values
                                                        .SelectMany(x => x.Errors)
                                                        .Select(x => x.ErrorMessage))
                });
            }
            if (status == "true")
            {
                //TempData["MessageTC"] = message;
                //TempData["StatusTC"] = status;
                return Json(new { status = status, message = message });
            }
            else
            {
                //ViewBag.Message = message;
                //ViewBag.Status = status;
                return Json(new { status = status, message = message });
            }
        }
        public ActionResult Delete_Factors(string id, string module_id, string module_name)
        {
            String status = "false";
            String message = "";            
            using (var context = new DBModels())
            {
                try
                {
                    int id2 = Int32.Parse(id);
                    int module_id2 = Int32.Parse(module_id);
                    var itemToRemove = context.factors_name_table.SingleOrDefault(x => x.fn_id == id2);

                    if (itemToRemove != null)
                    {
                        context.factors_name_table.Remove(itemToRemove);
                        var response = context.SaveChanges();
                        status = "true";
                        message = "Successfully";
                    }
                    else
                    {
                        status = "false";
                        message = "fn_id not found";
                    }
                }
                catch (Exception ex)
                {
                    status = "false";
                    message = ex.Message;
                }
            }
            //TempData["MessageTC"] = message;
            //TempData["StatusTC"] = status;
            return Json(new { status = status, message = message });
        }
    }
}

WebTest2/Views/AddFactors/Display_Factors.cshtml
@model WebTest2.Models.listFactors

@{
    ViewBag.Title = "Test Scenario";
}
@*<link href="~/Content/Vertical.css" rel="stylesheet" />*@
<h2>Add Factors</h2>
@if (TempData["MessageTC"] != null && TempData["StatusTC"].ToString() == "true")
{
    <div class="alert alert-success" role="alert">
        @TempData["MessageTC"].ToString()
    </div>
}
else if (TempData["MessageTC"] != null && TempData["StatusTC"].ToString() == "false")
{
    <div class="alert alert-danger" role="alert">
        @TempData["MessageTC"].ToString()
    </div>
}

@*<button type="button" class="btn btn-light">@Html.ActionLink("Add New Factors", "add_new_factors", new { id = @ViewBag.Module_id, module_name = @ViewBag.MName })</button>*@
@*<button type="button" class="btn btn-success">Generate Test Scenario</button>*@
@*<em>@ViewBag.TotalFactor Test Scenarios</em>*@

@using (Ajax.BeginForm("Add_new_Factors", "AddFactors", new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxAddSuccess(data);", OnFailure = "ajaxAddUnSuccess(data);" }))
{
    @Html.AntiForgeryToken()

<div class="form-row">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-2">
        <div class="form-group">                  
            @Html.EditorFor(model => model.factors_Name_Table.fn_name, new { htmlAttributes = new { @class = "form-control", @id = "factors_name" } })
            @Html.ValidationMessageFor(model => model.factors_Name_Table.fn_name, "", new { @class = "text-danger" })
            @if (ViewBag.Module_id != null)
            {
                <input type="hidden" name="module_id" id="module_id" value="@ViewBag.Module_id" />
            }
            else
            {
                @Html.EditorFor(model => model.factors_Name_Table.module_id, new { htmlAttributes = new { @type = "hidden", @class = "form-control", @id = "module_id" } })
            }
        </div>
    </div>
    <div class="col-1">
        <div class="form-group">            
                <input type="submit" value="Add" class="btn btn-info" />        
        </div>
    </div>
</div>
}



<table class="table" id="factors_table">
    <tr>
        <th>
            <h5>Factors</h5>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.factors_Name_Tables)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fn_name)
            </td>
            <td>
                @Html.ActionLink("Add Factor Items", "Display_Items_Factors", "AddItems", new { id = item.fn_id, module_id = @ViewBag.Module_id, module_name = @ViewBag.MName }, new { @class = "link" }) | <a href="#" name="del_fn" id="del_fn"  onclick='delfn("@item.fn_id","@item.fn_name","@ViewBag.Module_id","@ViewBag.MName");'>Delete</a>
            </td>
        </tr>
    }

</table>

<div>
    @*Back to previous page*@
    @if (Request.UrlReferrer != null)
    {
        <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back to Factors Page</a><br />
    }
</div>

@*render javascript*@
@section Scripts{

    <script>

        var ajaxAddSuccess = function (data) {
            if (data.status == "true") {
                //debugger;
                alert(data.message);
                $("#factors_table").load(" #factors_table > *");
                $('#factors_name').val('');
            } else {
                //debugger;
                alert(data.message);
                $('#factors_name').val('');
            }
        }

        var ajaxAddUnSuccess = function (data) {
            if (data.status == "true") {
                alert(data.message);
            } else {
                alert(data.message);
            }
            
        }

        function delfn(ID,FNNMAE,MID,MNMAE) {
            //debugger;
            var ans = confirm("Are you sure you want to delete " + FNNMAE + " ? ");
            if (ans) {
                $.ajax({
                    url: "/AddFactors/Delete_Factors",
                    type: "POST",
                    dataType: "json",
                    data: { 'id': ID, 'module_id': MID, 'module_name': MNMAE },
                    success: function (result) {
                        if (result.status == "true") {
                            alert(result.message);
                        } else {
                            alert(result.message);
                        }
                        $("#factors_table").load(" #factors_table > *");
                    },
                    error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }

                        alert(msg);
                    }
                });
            }
        }
        var navbar_name = document.getElementById("navbar-brand");
        navbar_name.innerHTML = "@ViewBag.MName";

        const div = document.createElement('div');

                div.className = 'row';

                div.innerHTML = `
                                <div class="collapse navbar-collapse" id="navbarNav">
                                    <ul class="navbar-nav">
                                        <li class="nav-item active">
                                            @Html.ActionLink("Test Scenario", "Display_Factors","AddFactors", new { id = @ViewBag.Module_id, module_name = @ViewBag.MName },new { @class= "nav-link" })
                                        </li>
                                    </ul>
                                </div>
                                `;

                document.getElementById('navbar').appendChild(div);
    </script>


}